#!/bin/bash
#
#                             MIT License
#
# Copyright (c) 2021 Futurewei Technologies Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#


. dr_lib

sanity_check_cfg

#set -x

sanity_check_file_exist csi_bin.tgz
if [ ! -d csi_bin ];then
   mkdir -p csi_bin
   tar -xzf csi_bin.tgz -C csi_bin
fi

cd csi_bin

#TODO: update hard coded IPs in yaml
kubectl apply -f huawei-csi-rbac.yaml
kubectl apply -f huawei-csi-configmap-oceanstor-iscsi.yaml
kubectl apply -f huawei-csi-controller.yaml
kubectl apply -f huawei-csi-node.yaml
kubectl apply -f storage-class.yaml

ssh $PEER kubectl apply -f huawei-csi-rbac.yaml
ssh $PEER kubectl apply -f huawei-csi-configmap-oceanstor-iscsi-secondary.yaml
ssh $PEER kubectl apply -f huawei-csi-controller.yaml
ssh $PEER kubectl apply -f huawei-csi-node.yaml
ssh $PEER kubectl apply -f storage-class-replica.yaml




