#!/bin/bash

. dr_lib

sanity_check_cfg

#set -x

sanity_check_file_exist csi_bin.tgz
if [ ! -d csi_bin ];then
   mkdir -p csi_bin
   tar -xzf csi_bin.tgz -C csi_bin
fi

cd csi_bin

#TODO: update hard coded IPs in yaml
kubectl apply -f huawei-csi-rbac.yaml
kubectl apply -f huawei-csi-configmap-oceanstor-iscsi.yaml
kubectl apply -f huawei-csi-controller.yaml
kubectl apply -f huawei-csi-node.yaml
kubectl apply -f storage-class.yaml

ssh $PEER kubectl apply -f huawei-csi-rbac.yaml
ssh $PEER kubectl apply -f huawei-csi-configmap-oceanstor-iscsi-secondary.yaml
ssh $PEER kubectl apply -f huawei-csi-controller.yaml
ssh $PEER kubectl apply -f huawei-csi-node.yaml
ssh $PEER kubectl apply -f storage-class-replica.yaml




