#!/bin/bash
#
#                             MIT License
#
# Copyright (c) 2021 Futurewei Technologies Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#



echo execute this script on a k8s node with ceph nodes injected into /etc/hosts

CEPHA='ceph3-1'
CEPHB='ceph4-1'
#OUTPUT=/devhub/fksdr/template/csi-config-map-$$.yaml
OUTPUT=/devhub/fksdr/template/csi-config-map.yaml

gen_segment()
{
   FSID="`ssh $1 cat /etc/ceph/ceph.conf | grep fsid | awk '{print $3}'`"
   IP="`grep $1 /etc/hosts | awk '{print $1}'`"
   cat <<EOF
        "clusterID": "$FSID",
        "monitors": [
          "$IP:6789",
          "$IP:6789",
        ]
EOF
}

SEGA="`gen_segment $CEPHA`"
SEGB="`gen_segment $CEPHB`"

#cat /devhub/fksdr/template/csi-config-map.yaml.template | sed "s/FSID/$FSID/g;s/IP/$IP/g" | tee $OUTPUT

cat > $OUTPUT <<EOF
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
$SEGA
      },
      {
$SEGB
      },
    ]
metadata:
  name: ceph-csi-config
  namespace: ceph-csi-rbd

EOF

