#!/bin/bash
#
#                             MIT License
#
# Copyright (c) 2021 Futurewei Technologies Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#



echo execute this script on a ceph mon noed

FSID="`cat /etc/ceph/ceph.conf | grep fsid | awk '{print $3}'`"
#echo FSID: $FSID

USERKEY="`cat /etc/ceph/ceph.client.admin.keyring | grep key | awk '{print $3}'`"
#echo USERKEY: $USERKEY

SECNAME=ceph-csi-rbd-sec
cat /devhub/fksdr/template/ceph_sc.yaml.template | sed "s/FSID/$FSID/g;s/USERKEY/$USERKEY/g;s/SECNAME/$SECNAME/g" | tee /devhub/fksdr/template/ceph_sc-`hostname`.yaml

